name: Build tars library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      CONAN_REVISIONS_ENABLED: 1
    strategy:
      matrix:
        os: [ macos-13, ubuntu-22.04, windows-latest ]
    steps:
      - name: Check out Git repositorygit
        uses: actions/checkout@v1
      - name: Install Dependency
        run: pip3 install -r requirements.txt
      - name: Setup Conan Remote
        run: |
          conan remote add conan https://conan.bzdrs.cn/artifactory/api/conan/conan
          conan user -p ${{ secrets.CONAN_SECRET }} -r conan admin
      - name: Build Debug
        run: conan create . _/_ --build=missing -sbuild_type=Debug
      - name: Upload Debug
        run: conan upload tars/3.0.13 --all -r conan --retry 3 --retry-wait 10 --confirm --parallel
      - name: Build Release
        run: conan create . _/_ --build=missing -sbuild_type=Release
      - name: Upload Release
        run: conan upload tars/3.0.13 --all -r conan --retry 3 --retry-wait 10 --confirm --parallel